# Generated by Django 5.1.1 on 2024-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "lineNo",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Line Number"
                    ),
                ),
                ("productName", models.TextField(verbose_name="Product Name")),
                ("unitNo", models.IntegerField(verbose_name="Unit Number")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="quantity"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Total"
                    ),
                ),
                ("expiryDate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "unitNo",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Unit Number"
                    ),
                ),
                (
                    "unitName",
                    models.CharField(max_length=100, verbose_name="Unit Name"),
                ),
            ],
        ),
    ]
